<?php

require_once('cnapi_extras.preprocess.inc');

/**
 * Implements hook_block_info().
 */
function cnapi_extras_block_info() {
  $block['wider_radius_search']['info'] = t('CultuurNet API wider radius search');
  $block['wider_radius_search']['cache'] = DRUPAL_CACHE_PER_PAGE;
  
  $block['movie_results']['info'] = t('Movie results');
  $block['movie_results']['cache'] = DRUPAL_CACHE_PER_PAGE;

  return $block;
}

/**
 * Implements hook_block_view().
 */
function cnapi_extras_block_view($delta = '') {
  module_load_include('inc', 'cnapi_extras', 'cnapi_extras.blocks');

  if (function_exists('cnapi_extras_block_' . $delta)) {
    return call_user_func('cnapi_extras_block_' . $delta);
  }
}

/**
 * Implements hook_theme().
 */
function cnapi_extras_theme() {
  return array(
    'cnapi_extras_block_wider_radius_search' => array(
      'variables' => array('request_type' => NULL, 'city' => NULL, 'city_type' => NULL, 'radius' => NULL, 'request' => NULL, 'data' => NULL, 'total' => NULL),
      'template' => 'cnapi-extras-block-wider-radius-search',
    ),
    'cnapi_extras_block_movie_results' => array(
      'variables' => array('productions' => NULL, 'form' => NULL, 'total' => NULL, 'more_request' => NULL),
      'template' => 'cnapi-extras-block-movie-results',
    ),
    'cnapi_extras_movie_summary' => array(
      'variables' => array('production' => NULL),
      'template' => 'cnapi-extras-block-movie',
    ),
  );
}

function cnapi_extras_movie_search_form($form, &$form_state) {
  $form = array();

  $context = cnapi_ui_contexts('id', 'movie');
  
  $query = $context['query'];
  
  $options = array();
  
  $report = cnapi_get_report('production', $query);
  $productions = $report['production'];
  foreach ($productions as $cdbid => $production) {
    $options[$cdbid] = $production['name'];
  }
  
  asort($options);
  
  $options = array(CNAPI_OPTION_NONE => 'Selecteer een locatie') + $options;

  $form['cdbid'] = array(
    '#type' => 'select',
    '#title' => t('Production'),
    '#options' => $options,
    '#default_value' => isset($request['query']['cdbid']) ? $request['query']['cdbid'] : '',
    '#attributes' => array('class' => array('autosubmit')),
  );
  
  $options = array();
  foreach ($report['location'] as $id => $location) {
    $options[$id] = $location['name'];
  }
  
  asort($options);
  
  $options = array(CNAPI_OPTION_NONE => 'Selecteer een locatie') + $options;
  
  $form['location'] = array(
    '#type' => 'select',
    '#title' => 'Locatie',
    '#options' => $options,
    '#attributes' => array('class' => array('autosubmit')),
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Filter',
  );
  
  return $form;
}

function cnapi_extras_movie_search_form_submit($form, &$form_state) {
  // The search form relies on control of the redirect destination for its
  // functionality, so we override any static destination set in the request,
  // for example by drupal_access_denied() or drupal_not_found()
  // (see http://drupal.org/node/292565).
  if (isset($_GET['destination'])) {
    unset($_GET['destination']);
  }

  // initialising the request object with the event context
  $request = array('context' => 'movie');

  cnapi_browse_process_form_values($request, $form_state['values']);

  cnapi_ui_goto($request);
}