<?php

require_once('cnapi_ui.params.inc');
require_once('cnapi_ui.helpers.inc');
require_once('cnapi_ui.seo.inc');
require_once('cnapi_ui.preprocess.inc');

/**
 * Implements hook_menu().
 */
function cnapi_ui_menu() {
  $contexts = cnapi_ui_contexts();
  foreach ($contexts as $context => $info) {
    $path = $info['path'];
    $type = $info['type'];

    $items[$path] = array(
      'title' => 'List',
      'page callback' => 'cnapi_ui_page_list',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
      'file' => 'cnapi_ui.pages.inc',
    );
  }

  return $items;
}

/**
 * Implements hook_init().
 */
function cnapi_ui_init() {
  cnapi_ui_set_canonical_and_noindex();
  cnapi_ui_seo_redirects();
}

/**
 * Implements hook_theme().
 */
function cnapi_ui_theme() {
  return array(
    'cnapi_ui_actor_summary' => array(
      'variables' => array('actor' => NULL),
      'template' => 'cnapi-ui-actor-summary',
    ),
    'cnapi_ui_event_summary' => array(
      'variables' => array('event' => NULL),
      'template' => 'cnapi-ui-event-summary',
    ),
    'cnapi_ui_production_summary' => array(
      'variables' => array('production' => NULL),
      'template' => 'cnapi-ui-production-summary',
    ),
  );
}

function cnapi_ui_contexts($key = 'id', $id = NULL) {
  $contexts = &drupal_static(__FUNCTION__, NULL);
  
  if (!$contexts) {
    $contexts['id'] = array(
      'event' => array(
        'id' => 'event',
        'type' => 'event',
        'query' => array('locationtype' => '!8.9.1.0.0'),
        'path' => 'agenda/search',
      ),
      'actor' => array(
        'id' => 'actor',
        'type' => 'actor',
        'query' => array(),
        'path' => 'agenda/ar',
      ),
      'movie' => array(
        'id' => 'movie',
        'type' => 'production',
        'query' => array('type' => '0.50.6.0.0'),
        'path' => 'agenda/film',
      ),
      'movie_children' => array(
        'id' => 'movie_children',
        'type' => 'production',
        'query' => array('type' => '0.50.6.0.0', 'age' => '1..11'),
        'path' => 'agenda/film/kinderen'
      ),
    );
    
    drupal_alter('cnapi_ui_contexts', $contexts);
    
    $contexts['path'] = array();

    foreach ($contexts['id'] as $context => $info) {
      $path = $info['path'];

      $contexts['path'][$path] = $info;
    }
  }

  if ($id) {
    return isset($contexts[$key][$id]) ? $contexts[$key][$id] : NULL;
  }

  return $contexts[$key];
}