<?php

require_once('cnapi_ui.params.inc');
require_once('cnapi_ui.helpers.inc');
require_once('cnapi_ui.seo.inc');
require_once('cnapi_ui.preprocess.inc');

/**
 * Implements hook_menu().
 */
function cnapi_ui_menu() {
  $contexts = cnapi_ui_contexts();
  foreach ($contexts as $context => $info) {
    $path = $info['path'];
    $type = $info['type'];

    // Menu path for list pages.
    $items[$path] = array(
      'title' => 'List',
      'page callback' => 'cnapi_ui_page_list',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
      'file' => 'cnapi_ui.pages.inc',
    );

    // Menu path for RSS.
    $items['rss/' . $path] = array(
      'title' => 'RSS',
      'page callback' => 'cnapi_ui_page_list_rss',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
      'file' => 'cnapi_ui.pages.inc',
    );
  }

  return $items;
}

/**
 * Implements hook_init().
 */
function cnapi_ui_init() {
  // Setting SEO canonical and noindex.
  cnapi_ui_set_canonical_and_noindex();

  // SEO redirects for details pages.
  cnapi_ui_seo_redirects();

  // CultuurNet API tracking calls in case tracking is enabled.s
  if (module_exists('cnapi_tracking')) {
    module_load_include('inc', 'cnapi_ui', 'cnapi_ui.tracking');
    cnapi_ui_tracking();
  }
}

/**
 * Implements hook_theme().
 */
function cnapi_ui_theme() {
  return array(
    'cnapi_ui_actor' => array(
      'variables' => array('actor' => NULL),
      'template' => 'cnapi-ui-actor',
    ),
    'cnapi_ui_event' => array(
      'variables' => array('event' => NULL),
      'template' => 'cnapi-ui-event',
    ),
    'cnapi_ui_production' => array(
      'variables' => array('production' => NULL),
      'template' => 'cnapi-ui-production',
    ),
    'cnapi_ui_actor_summary' => array(
      'variables' => array('actor' => NULL, 'url_absolute' => FALSE),
      'template' => 'cnapi-ui-actor-summary',
    ),
    'cnapi_ui_event_summary' => array(
      'variables' => array('event' => NULL, 'url_absolute' => FALSE),
      'template' => 'cnapi-ui-event-summary',
    ),
    'cnapi_ui_production_summary' => array(
      'variables' => array('production' => NULL, 'url_absolute' => FALSE),
      'template' => 'cnapi-ui-production-summary',
    ),
    'cnapi_ui_page_list_rss' => array(
      'variables' => array('objects' => array(), 'type' => NULL),
    ),
  );
}

function cnapi_ui_contexts($key = 'id', $id = NULL) {
  $contexts = &drupal_static(__FUNCTION__, NULL);

  if (!$contexts) {
    $contexts['id'] = array(
      'event' => array(
        'id' => 'event',
        'type' => 'event',
        'query' => array('locationtype' => '!8.9.1.0.0'),
        'path' => 'agenda/search',
      ),
      'actor' => array(
        'id' => 'actor',
        'type' => 'actor',
        'query' => array(),
        'path' => 'agenda/ar',
      ),
      'movie' => array(
        'id' => 'movie',
        'type' => 'production',
        'query' => array('type' => '0.50.6.0.0'),
        'path' => 'agenda/film',
      ),
      'movie_children' => array(
        'id' => 'movie_children',
        'type' => 'production',
        'query' => array('type' => '0.50.6.0.0', 'age' => '1..11'),
        'path' => 'agenda/film/kinderen'
      ),
    );

    drupal_alter('cnapi_ui_contexts', $contexts['id']);

    $contexts['path'] = array();

    foreach ($contexts['id'] as $context => $info) {
      $path = $info['path'];

      $contexts['path'][$path] = $info;
    }
  }

  if ($id) {
    return isset($contexts[$key][$id]) ? $contexts[$key][$id] : NULL;
  }

  return $contexts[$key];
}

function theme_cnapi_ui_page_list_rss($variables) {
  $objects = $variables['objects'];
  $type = $variables['type'];

  $items = array();
  if ($objects) {
    foreach ($objects as $object) {
      // object_url
      $request_detail = array($type => $object['cdbid'], 'title' => $object['title']);

      $object_url = cnapi_url_dp2dua($request_detail);
      $object_url['options']['absolute'] = TRUE;
      $object_url = url($object_url['path'], $object_url['options']);

      $args = array(
        array('key' => 'pubDate', 'value' => date('r', $object['created'])),
        array('key' => 'guid', 'value' => $object_url, 'attributes' => array('isPermaLink' => 'true')),
        array('key' => 'postid', 'value' => $object['cdbid']),
      );

      $body = theme('cnapi_ui_' . $type . '_summary', array($type => $object, 'url_absolute' => TRUE));
      $items .= format_rss_item($object['title'], $object_url, $body, $args);
    }
  }

  $site_name = variable_get('site_name', 'Drupal');
  $url['options']['absolute'] = TRUE;
  $url = url($url['path'], $url['options']);
  $description = 'Description of feed.';

  $output  = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
  $output .= "<rss version=\"2.0\">\n";
  $output .= format_rss_channel(t('@site_name', array('@site_name' => $site_name)), $url, $description, $items);
  $output .= "</rss>\n";

  return $output;
}